const kidsData = [
  {
    name: "Emma",
    age: 7,
    price: 25.99,
    imageUrl: "emma.png",
    altText: "an image of a child",
  },
  {
    name: "Liam",
    age: 8,
    price: 30.0,
    imageUrl: "liam.png",
    altText: "an image of a child",
  },
  {
    name: "Olivia",
    age: 6,
    price: 22.99,
    imageUrl: "olivia.png",
    altText: "an image of a child",
  },
  {
    name: "Noah",
    age: 9,
    price: 28.0,
    imageUrl: "noah.png",
    altText: "an image of a child",
  },
  {
    name: "Ava",
    age: 5,
    price: 20.99,
    imageUrl: "ava.png",
    altText: "an image of a child",
  },
  {
    name: "Elijah",
    age: 10,
    price: 33.0,
    imageUrl: "elijah.png",
    altText: "an image of a child",
  },
  {
    name: "Sophia",
    age: 4,
    price: 18.99,
    imageUrl: "sophia.png",
    altText: "an image of a child",
  },
  {
    name: "James",
    age: 11,
    price: 35.0,
    imageUrl: "james.png",
    altText: "an image of a child",
  },
  {
    name: "Amelia",
    age: 8,
    price: 29.99,
    mageUrl: "amelia.png",
    altText: "an image of a child",
  },
  {
    name: "Isabella",
    age: 7,
    price: 27.0,
    imageUrl: "isabella.png",
    altText: "an image of a child",
  },
  {
    name: "Lucas",
    age: 9,
    rice: 32.99,
    imageUrl: "lucas.png",
    altText: "an image of a child",
  },
  {
    name: "Mia",
    age: 6,
    price: 21.0,
    imageUrl: "mia.png",
    altText: "an image of a child",
  },
  {
    name: "Mason",
    age: 5,
    price: 19.99,
    imageUrl: "mason.png",
    altText: "an image of a child",
  },
  {
    name: "Charlotte",
    age: 10,
    price: 34.0,
    imageUrl: "charlotte.png",
    altText: "an image of a child",
  },
  {
    name: "Logan",
    age: 8,
    price: 26.99,
    imageUrl: "logan.png",
    altText: "an image of a child",
  },
  {
    name: "Harper",
    age: 4,
    price: 17.0,
    imageUrl: "harper.png",
    altText: "an image of a child",
  },
  {
    name: "Ethan",
    age: 11,
    price: 36.99,
    imageUrl: "ethan.png",
    altText: "an image of a child",
  },
  {
    name: "Evelyn",
    age: 7,
    price: 24.0,
    imageUrl: "evelyn.png",
    altText: "an image of a child",
  },
  {
    name: "Alexander",
    age: 9,
    price: 31.99,
    imageUrl: "alexander.png",
    altText: "an image of a child",
  },
  {
    name: "Everton Henriques",
    age: 40,
    price: 1200.0,
    imageUrl: "everton henriques.png",
    altText: "an image of Mr. Henriques",
  },
];

export { kidsData };
